repos:
- repo: https://github.com/commitizen-tools/commitizen
  rev: v4.9.1
  hooks:
  - id: commitizen
    stages: [commit-msg]
  - id: commitizen-branch
    stages: [pre-push]
    args: [--rev-range, origin/main..HEAD]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: debug-statements
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.13.0
  hooks:
  - id: ruff
    args: [--fix]
  - id: ruff-format
