name: Pre-commit Auto-update

on:
  schedule:
    # Run weekly on Sunday at midnight UTC
    - cron: '0 0 * * 0'
  workflow_dispatch:  # Allow manual triggering

jobs:
  autoupdate:
    name: Auto-update pre-commit hooks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit autoupdate
        run: pre-commit autoupdate

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: pre-commit-autoupdate
          title: 'chore: update pre-commit hooks'
          commit-message: 'chore: update pre-commit hooks'
          body: |
            Auto-update pre-commit hooks to latest versions.

            - Updated by [pre-commit-autoupdate workflow](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
          delete-branch: true
